FROM quay.io/fedora/fedora-toolbox:43

RUN dnf install -y \
vim git make \
python3 python3-devel \
python3-pytest python3-pytest-sugar mypy \
rust cargo

RUN dnf install -y \
python3-click \
python3-yaml python3-types-pyyaml \
python3-requests python3-types-requests \
python3-torch

RUN dnf install -y \
sphinx python3-sphinx_rtd_theme

RUN pip install tiktoken

RUN dnf clean all
